// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyoDsYbWEv5a_mZRIOv7Nx5eSvJU-PYqY',
    appId: '1:616298979273:web:66f15e8036a9930136d218',
    messagingSenderId: '616298979273',
    projectId: 'agrogestor-5328c',
    authDomain: 'agrogestor-5328c.firebaseapp.com',
    storageBucket: 'agrogestor-5328c.firebasestorage.app',
    measurementId: 'G-4KM7CPZ6MP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBu9pBJnpW_Uqp7TiKtsIk5ANGafub8lQ',
    appId: '1:616298979273:android:1996b5bf11c678ab36d218',
    messagingSenderId: '616298979273',
    projectId: 'agrogestor-5328c',
    storageBucket: 'agrogestor-5328c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyoDsYbWEv5a_mZRIOv7Nx5eSvJU-PYqY',
    appId: '1:616298979273:web:4cd1d6a6f24b863436d218',
    messagingSenderId: '616298979273',
    projectId: 'agrogestor-5328c',
    authDomain: 'agrogestor-5328c.firebaseapp.com',
    storageBucket: 'agrogestor-5328c.firebasestorage.app',
    measurementId: 'G-0Z0HCEKRRQ',
  );
}
